version: '3.1'

services:
  db:
    build: .
    image: mysql:8.0
    container_name: Control_Academico
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: controlacademico
    ports:
      - 3306:3306
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d